name: Docker Image CI

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   compile:
      name: Compile .tex to .pdf and .pdf to .jpg
      runs-on: ubuntu-latest

      steps:
         - name: Check out the repo
           uses: actions/checkout@v4

         - name: Set up Docker
           uses: docker/setup-buildx-action@v2

         - name: Run the build process with Docker
           uses: addnab/docker-run-action@v3
           with:
              image: babdikaarov/latex:latest
              options: -v ${{ github.workspace }}:/data
              run: |
                 cd /data
                 for file in *.tex; do \
                   base=$(basename "$file" .tex); \
                   pdflatex "$file"; \
                   convert -density 300 "$base.pdf" -quality 100 "$base.jpg"; \
                 done

         - name: List files in the repository root
           run: ls -al /home/runner/work/cv/cv

         - name: Fix file permissions
           run: sudo chown -R runner:docker /home/runner/work/cv/cv/*.jpg /home/runner/work/cv/cv/*.pdf

         - name: Sleep for 5 seconds
           run: sleep 5

         - name: Debug Git Status
           run: |
             git status
             git ls-files
             git diff --name-only

         - name: Commit generated files
           uses: stefanzweifel/git-auto-commit-action@v5
           with:
              commit_message: Apply pdflatex and image conversion changes
              file_pattern: "*.pdf *.jpg"
              branch: main
              skip_dirty_check: false