name: Docker Image CI

on:
   push:
      branches: [main]
      # paths:
      #    - "**/*.tex"
   pull_request:
      branches: [main]
      # paths:
      #    - "**/*.tex"

jobs:
   compile:
      name: Compile .tex to .pdf and .pdf to .jpg
      runs-on: ubuntu-latest

      steps:
         - name: Check out the repo
           uses: actions/checkout@v4

         - name: Set up Docker
           uses: docker/setup-buildx-action@v2

         - name: Run the build process with Docker
           uses: addnab/docker-run-action@v3
           with:
              image: babdikaarov/latex:latest
              options: -v ${{ github.workspace }}:/data
              run: |
                 cd /data
                 for file in *.tex; do \
                   base=$(basename "$file" .tex); \
                   pdflatex "$file"; \
                   convert -density 300 "$base.pdf" -quality 100 "$base.jpg"; \
                 done
         - name: List files
           run: ls -al 
         - name: CURRENT DIRECTORY
           run: pwd
         - name: Debug Git Status
           run: |
              git status
              git diff
         - name: Commit generated files
           uses: stefanzweifel/git-auto-commit-action@v5
           with:
              commit_message: Apply pdflatex and image conversion changes
              file_pattern: "*.pdf *.jpg **/*.pdf **/*.jpg"
              branch: main
              skip_dirty_check: false
